name: pack from deb

on:
  push:
    paths:
      - .github/workflows/deb.yaml
      - deb/*
      - VERSION
  pull_request:
    paths:
      - .github/workflows/deb.yaml
      - deb/*
  workflow_dispatch:

env:
  GHCR_REPO: ghcr.io/${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set version
        run: echo "version=`cat VERSION`" >> $GITHUB_ENV

      - name: Set tags
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            echo "TAGS=${{ env.GHCR_REPO }}:latest,${{ env.GHCR_REPO }}:${{ env.version }}" >> "$GITHUB_ENV"
          else
            echo "TAGS=${{ env.GHCR_REPO }}:deb-${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build image without push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./deb
          file: ./deb/Dockerfile
          load: true
          tags: protonmail-bridge:latest

      - name: Scan image
        id: scan
        uses: anchore/scan-action@1638637db639e0ade3258b51db49a9a137574c3e # v6
        with:
          image: protonmail-bridge:latest
          fail-build: true
          severity-cutoff: critical

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./deb
          file: ./deb/Dockerfile
          tags: ${{ env.TAGS }}
          push: ${{ github.event_name != 'pull_request' }}
